language: clojure
script: boot test
before_install:
 - sudo apt-get --yes install wget
before_script:
  - "echo 'Getting ipfs-update'"
  - wget https://dist.ipfs.io/ipfs-update/v1.5.2/ipfs-update_v1.5.2_linux-amd64.tar.gz -o ipfs-update.tar.gz
  - "echo 'Extracting'"
  - tar -xzf ipfs-update.tar.gz
  - "echo 'Installing latest IPFS'"
  - ipfs-update install latest
  - "echo 'Running IPFS daemon'"
  - ipfs daemon > /dev/null &
